workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS Simulator .app (DEBUG)
        script: |
          set -e
          flutter --version
          flutter build ios --simulator --debug

          echo "Listing build/ios/iphonesimulator:"
          ls -la build/ios/iphonesimulator || true

          cd build/ios/iphonesimulator
          zip -r -y MuseoRapaNui.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/MuseoRapaNui.app.zip
