workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    instance_type: mac_mini_m2

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS Simulator .app
        script: |
          flutter build ios --simulator --release
          cd build/ios/iphonesimulator
          zip -r MuseoRapaNui.app.zip Runner.app

    artifacts:
      - build/ios/iphonesimulator/MuseoRapaNui.app.zip
