workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter pub get
        script: |
          flutter --version
          flutter pub get

      - name: Build iOS Simulator app (DEBUG)
        script: |
          set -e

          flutter build ios --simulator --debug --no-codesign

          echo "Finding .app in build/ios/iphonesimulator ..."
          APP_PATH=$(find build/ios/iphonesimulator -maxdepth 1 -type d -name "*.app" | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "❌ No .app found in build/ios/iphonesimulator"
            echo "Listing build/ios:"
            ls -la build/ios || true
            echo "Listing build/ios/iphonesimulator:"
            ls -la build/ios/iphonesimulator || true
            exit 1
          fi

          echo "✅ Found app: $APP_PATH"

          cd "$(dirname "$APP_PATH")"
          APP_NAME="$(basename "$APP_PATH")"
          ZIP_NAME="${APP_NAME%.app}.app.zip"

          rm -f "$ZIP_NAME"
          /usr/bin/zip -r "$ZIP_NAME" "$APP_NAME"
          echo "✅ Zipped: $(pwd)/$ZIP_NAME"

      # (Opcional) Si querés screenshots automáticas, descomentá este step.
      # OJO: requiere que el build del simulador funcione bien primero.
      #
      # - name: Take screenshots (optional)
      #   script: |
      #     set -e
      #     xcrun simctl list devices available
      #     # Acá podés agregar tu script de screenshots si ya lo tenés armado.

    artifacts:
      - build/ios/iphonesimulator/*.zip
      - build/ios/iphonesimulator/*.app.zip
      - flutter_drive.log
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - qgonzalez@unbcollections.com.ar
        notify:
          success: true
          failure: true
